FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV ASPNETCORE_ENVIRONMENT Development

COPY ./src/Mutterblack.Bot/*.csproj /tmp/
COPY ./Directory.Build.props /

WORKDIR /tmp

RUN dotnet restore

WORKDIR /app/Mutterblack.Bot

ENTRYPOINT dotnet watch run --no-launch-profile